<a href="https://colab.research.google.com/github/iitmanushka137/PDSA_Python/blob/main/Graphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
pip install numpy

In [ ]:
D={}
for i in range(n):
  D[i]=[]
for (i,j) in edges:#list of edges (i,j) such that there is an edge from i to j
  D[i].append(j)
print(D)

In [2]:
import numpy as np
A=np.zeros(shape=(10,10))

# Directed Graph

Adjacency Matrix

In [9]:
import numpy as np
V=[0, 1, 2, 3, 4]
E=[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
#Adjacency Matrix Creation
n=len(V)
Amat=np.zeros(shape=(n,n))
'''Amat=[]
for i in range(n):
  row=[]
  for j in range(n):
    row.append(0)
  Amat.append(row.copy())'''
for (i,j) in E:
  Amat[i,j]=1#Amat[i][j]=1

print(Amat)

[[0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


Adjacency List

In [10]:
V=[0, 1, 2, 3, 4]
E=[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
d={}
for i in V:
  d[i]=[]
for (i,j) in E:
  d[i].append(j)
print(d)

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}


# Undirected Graph

Adjacency Matrix

In [12]:
V=[0, 1, 2, 3, 4]
E=[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
G=E+[(j,i) for (i,j) in E]
import numpy as np
Amat=np.zeros(shape=(len(V),len(V)))
'''Amat=[]
for i in range(len(V)):
  rows=[]
  for j in range(len(V)):
    rows.append(0)
  Amat.append(rows.copy())'''
for (i,j) in G:
  Amat[i,j]=1#Amat[i][j]=1
print(Amat)

[[0. 1. 1. 0. 0.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1.]
 [0. 1. 1. 1. 0.]]


Adjacency List

In [13]:
V=[0, 1, 2, 3, 4]
E=[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
G=E+[(j,i) for (i,j) in E]
d={}
for i in V:
  d[i]=[]
for (i,j) in G:
  d[i].append(j)
print(d)

{0: [1, 2], 1: [3, 4, 0], 2: [4, 3, 0], 3: [4, 1, 2], 4: [1, 2, 3]}


# Breadth First Search

In [17]:
pip install snoop

In [20]:
class Queue:
    def __init__(self):
        self.queue = []
    def addq(self,v):
        self.queue.append(v)
    def delq(self):
        v = None
        if not self.isempty():
            v = self.queue[0]
            self.queue = self.queue[1:]
        return(v)    
    def isempty(self):
        return(self.queue == [])
    def __str__(self):
        return(str(self.queue))

In [21]:
import snoop
@snoop
def BFSList(AList,v):
    visited = {}
    for i in AList.keys():
        visited[i] = False
    q = Queue()
    
    visited[v] = True
    q.addq(v)
    
    while(not q.isempty()):
        j = q.delq()
        for k in AList[j]:
            if (not visited[k]):
                visited[k] = True
                q.addq(k)               
    return(visited)